version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_au
    ports:
        - 3307:3306
    restart: always
    volumes: 
        - ./data:/var/lib/mysql
    environment:
      MYSQL_USER : test
      MYSQL_PASSWORD : P@ssw0rd
      MYSQL_ROOT_PASSWORD: P@ssw0rd
